[workspace]
members = [
    "chopin-core",
    "chopin-cli",
    "chopin-examples/basic-api",
    "chopin-examples/hello-world",
    "chopin-examples/benchmark",
    "chopin-examples/performance-mode",
]
resolver = "2"

[workspace.package]
version = "0.1.5"
edition = "2021"
license = "WTFPL"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
overflow-checks = false
